### ISSUE TITLE
How to access localForage instance from the store?

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt-community/localforage-module#2]
I want to have access to localForage instance from the Nuxt store, but in provided docs I only found examples related to accessing the instance via this.$localForage in components, but how can it be accessed in store?

**Comment by besnikh** [comment]
Did you find any solution ? 
I am facing same problem here... I can access it from components but not from Store

**Comment by AndrewBogdanovTSS** [comment]
@besnikh no I didn't, it looks like the creator of this plugin just forgot to implement such functionality. He only exposed it on the Vue instance that is available only inside components, but it wasn't added to this.app or somehow injected into the context object. I hope that I just am missing smth, but if I'm right - that's insane

**Comment by lifenautjoe** [comment]
Crap. I can confirm this is the case. @besnikh

**Comment by KodeStar** [comment]
Is this still the case? 3 years later? :/
